# Generated by Django 5.0.6 on 2024-07-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='xx', max_length=2, unique=True),
        ),
    ]
