# Generated by Django 5.0.6 on 2024-07-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_language_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='language',
            constraint=models.CheckConstraint(check=models.Q(('code', 'en'), ('code', 'es'), _connector='OR'), name='language_supported_only_en_or_es'),
        ),
    ]
