# Generated by Django 5.0.6 on 2024-10-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_lg',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='author',
            name='image_md',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='author',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
